### ISSUE TITLE
rename slack.post_message action to something sane

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2contrib#125]
`st2 action slack.post_message message="message"` come on. How about `say` or `post` ?

**Comment by Kami** [comment]
Originally I called it `send_message`, but then I changed my mind and renamed it to `post_message` so it matches the API method name.

I can call it something else, but I find post_message quite explicit and good :)

**Comment by jfryman** [comment]
Maybe we hold off on any major changes until we look at all the chat as an aggregate in our ChatOps sprint. May be a premature optimization.

**Comment by emedvedev** [comment]
Closing as stale: here in December, almost a year from when this issue was created, we're using `post_message` pretty much everywhere, including the `chatops` pack. :)
