### ISSUE TITLE
Slack Sensor Instability

### ISSUE THREAD

**Issue by ryandub** [StackStorm/st2contrib#175]
The messages coming through Slack's RTM API seem to be quite varied and may or may not contain certain data. For example, #174 addresses some of the variations in profile data. However, I have also seen some quirkiness with `data` not containing a `channel` key as well (I haven't dug in to find what these messages are yet, but that's weird - maybe private groups?). Here's a stacktrace from such an occurance:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/container/sensor_wrapper.py", line 336, in run
    self._sensor_instance.run()
  File "/usr/lib/python2.7/dist-packages/st2reactor/sensor/base.py", line 92, in run
    self.poll()
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 45, in poll
    self._handle_result(result=result)
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 75, in _handle_result
    handler_func(data=item)
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 87, in _handle_message
    channel_info = self._get_channel_info(channel_id=data['channel'])
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 122, in _get_channel_info
    channel=channel_id)['channel']
KeyError: 'channel'
```
Note: Line numbers may be off as I was poking around on this file a bit...

Ideally, I would like for the sensor to keep on trucking despite running into issues with a particular message. Would it be appropriate to wrap `self._handle_result(result=result)` in the [poll](https://github.com/StackStorm/st2contrib/blob/master/packs/slack/sensors/slack_sensor.py#L51) function in a `try`/`except` block? On error, it could log the event, but keep the sensor running.

Thoughts?

**Comment by Kami** [comment]
Will look into it tomorrow, but in short, I also pushed a did for missing user and channel key in #173

**Comment by Kami** [comment]
Alright - as noted above, my change in #173 fixes the deleted user / channel issue, but I also agree that wrapping handle_result in try / catch and (logging and) continuing on exception is an acceptable thing to do here.

In general, you want to propagate all the fatal exceptions and not swallow and quietly ignore them, but in this case is acceptable - invalid API key or some other fatal exception will still be propagated since we are only wrapping _handle_result.

**Comment by Kami** [comment]
@ryandub In short - feel free to open a PR with the try / except change. Just make sure you still log the exception in the except clause though :)
