### ISSUE TITLE
Message formatting for Hubot (ChatOps)

### ISSUE THREAD

**Issue by armab** [StackStorm/st2contrib#231]
Related to https://github.com/StackStorm/st2contrib/pull/230, which was not good enough to cover all problem cases.

Seems we can't use serializers like [`yaml/pyyaml dump`](https://github.com/StackStorm/st2contrib/blob/master/packs/hubot/actions/post_result.py#L16). Instead just format `stdout` and `stderr` messages and post to hubot as is.
The problem if data contains any unprintable characters like `\t` - it's not supported by Yaml spec.

Examples of ugly output:
![1](http://i.imgur.com/gztx7aZ.png)
----
![2](http://i.imgur.com/Rmbf01W.png)
Real command output can have pretty much of that.

#### Resources:
* http://stackoverflow.com/a/20863889/4533625
* http://www.yaml.org/spec/1.2/spec.html#id2776092

----
The intent is to have nice looking/readable output in ChatOps, close as possible to real terminal view.

**Comment by armab** [comment]
From IRC:

> [15:49] bubo47: Hm. Is there a way how to interpret characters such as '\n' in output of action and print it ?

**Comment by Kami** [comment]
This would again be responsibility of a per-adapter formatter.

**Comment by emedvedev** [comment]
This is rather a `hubot-stackstorm` issue, and also configurable in 1.2.0. @armab if you have time, please reproduce in the latest version and open the issue in hubot-stackstorm repo. We'll see how we can fix it if it's still there; the default template is Jinja-rendered now, so there should be an easy way to deal with it.

**Comment by armab** [comment]
Yeah, obsolete issue.

I'll check how it looks in new version.
I hope ... someday ... when other issues let me free :)
