### ISSUE TITLE
ca certificate path

### ISSUE THREAD

**Issue by amaline** [StackStorm/st2contrib#240]
Not sure many people will have this problem, but we operate behind a proxy that breaks SSL so we need to load our own certs.  Was receiving the following error:

- requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Had this issue playing with the slack pack so had to mod the post_message.py as follows.  There may be an easier way as I am no python expert.  Mostly I had to import urllib3 and use the PoolManager.  It looked like there would be an easier way with python 2.7.9, but I did not want to risk upgrading.  Wondering if there is a global way to fix this since I don't want to munge every pack that needs to make an external SSL call.

```
import json
import httplib
import urllib3

import requests

from st2actions.runners.pythonrunner import Action

__all__ = [
    'PostMessageAction'
]


class PostMessageAction(Action):
    def run(self, message, username=None, icon_emoji=None, channel=None,
            disable_formatting=False):
        config = self.config['post_message_action']
        username = username if username else config['username']
        icon_emoji = icon_emoji if icon_emoji else config.get('icon_emoji', None)
        channel = channel if channel else config.get('channel', None)

        headers = {}
        headers['Content-Type'] = 'application/x-www-form-urlencoded'
        body = {
            'username': username,
            'icon_emoji': icon_emoji,
            'text': message
        }

        if channel:
            body['channel'] = channel

        if disable_formatting:
            body['parse'] = 'none'

        data = 'payload=%s' % (json.dumps(body))

        if config.get('ca_certs',None) is None:
                http = urllib3.PoolManager()
        else:
                http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED',ca_certs=config['ca_certs'])

        response=http.urlopen('POST',url=config['webhook_url'],headers=headers,body=data)

        if response.status == httplib.OK:
            self.logger.info('Message successfully posted')
        else:
            failure_reason = ('Failed to post message: %s (status code: %s)' %
                              (response.reason, response.status))
            self.logger.exception(failure_reason)
            raise Exception(failure_reason)

        return True
```

**Comment by manasdk** [comment]
hmm ... changing each pack would be pretty obnoxious. It likely we can configure this at a platform level in StackStorm. Lets see what can be done.

**Comment by jfryman** [comment]
@amaline Have you tried adding your CA certs to the OS trusted store? As far as I understand, everything underneath the hood of `urllib3` is just OpenSSL bindings anyway. To that end, instead of adding a variable to an action, you could just have the OS trust the CA.

Here's a script and explanation of how to do this. https://www.madboa.com/geek/openssl/#verify-system

What do you think?

**Comment by amaline** [comment]
@jfryman I forked the st2express and modified the [Dockerfile](https://github.com/amaline/st2express/blob/master/docker/Dockerfile) by adding the certs to /usr/local/share/ca-certificates and running "update-ca-certificates", I think that should have done it.

**Comment by amaline** [comment]
OK, found if I start the docker container with the environmental variable REQUESTS_CA_BUNDLE set to /etc/ssl/certs/ca-certificates.crt, everything works.

docker run -it --net=host -e REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt amaline/st2 bash

**Comment by jfryman** [comment]
@amaline great to know! I'll add this to our documentation for others to find in the future.
