### ISSUE TITLE
post message failure

### ISSUE THREAD

**Issue by amaline** [StackStorm/st2contrib#246]
Any idea why this works

   # st2 run slack.post_message message="{text: '%%foo'}"

but this fails

   # st2 run slack.post_message message="{text: '%%bar'}"
```
....
id: 55a7f35049236703c5722d62
status: failed
result:
{
    "result": null,
    "exit_code": 1,
    "stderr": "st2.actions.python.PostMessageAction: ERROR    Failed to post message: Payload was not valid JSON (status code: 500)
None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/slack/actions/post_message.py", line 45, in run
    raise Exception(failure_reason)
Exception: Failed to post message: Payload was not valid JSON (status code: 500)
",
    "stdout": ""
}
```
definitely some type of url encoding issue. '%ff' fails, but '%fg' works.

**Comment by Kami** [comment]
We don't escape the string as far as I know so yeah, it's probably trying to interpolate the string or something along those lines.

I will have a look.

**Comment by Kami** [comment]
I tried to reproduce the issue using the latest version of hubot pack and hubot-stackstorm hubot plugin, but I can't. It works fine here:

```bash
python st2client/st2client/shell.py run hubot.post_message channel=hubot message="{text: '%%bar'}"
2015-07-19 21:31:22,805  WARNING - Auth API server is not available, skipping authentication.
..
id: 55ac799a0640fd7007adc3b4
status: succeeded
result: 
{
    "result": true, 
    "exit_code": 0, 
    "stderr": "st2.actions.python.PostMessageAction: INFO     Message successfully posted
", 
    "stdout": ""
}
```

I also looked at the action code and we don't do anything with the message (message is sent as JSON in the body).

@amaline Which version of hubot-stackstorm hubot plugin are you using? It looks like that in your case, for some reason, hubot fails to parse message as JSON.

**Comment by amaline** [comment]
@Kami , in the above example I am not using any bot at all, I am just using the slack pack directly.
```
st2 run slack.post_message message="{text: '%ff'}"
```
The hubot pack probably encodes the string before putting it into the json message which is probably the correct thing to do, so I am probably just using the slack pack incorrectly here and should run
```
st2 run slack.post_message message="{text: '%25ff'}"
```
which indeed does work.

**Comment by Kami** [comment]
@amaline Sorry, I totally misread your PR description (I read "hubot" instead of "slack").

In the hubot case it's sent as JSON in the body, but in the slack case it's sent in the body as form encoded value so you are right that it's probably something to do with encoding. I will have a look.

**Comment by Kami** [comment]
@amaline Good catch. I've pushed a fix in https://github.com/StackStorm/st2contrib/pull/248.

And sorry for the initial confusion :)

**Comment by manasdk** [comment]
Also might be worth looking at https://github.com/StackStorm/st2-slack

Lot more actions available in that pack.

**Comment by dzimine** [comment]
Shall we deprecate st2contrib/slack in favor of st2-slack? 
DZ>

**Comment by amaline** [comment]
Thanks, I overlooked st2-slack.
