### ISSUE TITLE
logstash/kibana integration is not working

### ISSUE THREAD

**Issue by gelato** [StackStorm/st2contrib#270]
None of this is working with current version of logstash, so what's the point in keeping this integration on the stackstorm's site list?

**Comment by dzimine** [comment]
> None of this is working with current version of logstash,

do you mean [logstash integration](https://github.com/StackStorm/st2contrib/tree/master/extra/logstash) or something else?

**Comment by gelato** [comment]
Yep, logstash integration and kibana dashboard. People can easily fix it if
they have any knowledge in logstash, but still - it's not working now.
18 авг. 2015 г. 5:25 пользователь "Dmitri Zimin(e)" <
notifications@github.com> написал:

**Comment by dzimine** [comment]
We'll likely face-lift it soon, but meantime, a contribution to adjust to new version is very welcome!

**Comment by lakshmi-kannan** [comment]
Closing as unproductive.
