### ISSUE TITLE
Where can I find example for the openstack pack?

### ISSUE THREAD

**Issue by chilicat** [StackStorm/st2contrib#273]
Where can I find example for the openstack pack?

**Comment by manasdk** [comment]
@chilicat Take a look at https://github.com/StackStorm/openstack

Its a newer pack for openstack built on top of the CLI with some more actions etc. 

> Where can I find example for the openstack pack?
Are you looking for samples on how to use the pack or something else.

**Comment by chilicat** [comment]
I was already confused since I found https://github.com/StackStorm/openstack this and also a openstack pack in st2contrib. 

Is it preferred to use StackStorm/openstack? 

I was looking for simple examples like:  
1. Create a Instance 
2. attach floating ip 
3. get floating ip and report back to slack chat room. 

I used ansible for 1) 2) but I figured that ansible is not particular to extract information for further use in the workflow. Technically I could just write a script to extract the information I need but I wanted to see how far I get with the openstack packs.

**Comment by manasdk** [comment]
> Is it preferred to use StackStorm/openstack?
Yeah. Long term development will be on that pack.

> I was looking for simple examples like:
> 1. Create a Instance 

https://github.com/StackStorm/openstack/blob/master/actions/server.create.yaml

> 2. attach floating ip 

https://github.com/StackStorm/openstack/blob/master/actions/ip.floating.add.yaml

> 3. get floating ip and report back to slack chat room.
https://github.com/StackStorm/openstack/blob/master/actions/server.show.yaml

Should contain the floating-ip. To report back to slack from the chat-room you could either -
1. ChatOps the action (response automatically goes back to slack etc.)
2. Create a small workflow that explicitly posts to slack using our st2-slack pack (https://github.com/StackStorm/st2-slack/blob/master/actions/chat.postMessage.yaml)

I don't have a proper step-by-step recipe for you to follow at this point. This would require a bit of work but we have most of the disparate pieces out there already.

**Comment by chilicat** [comment]
I get following error:
```openstack server create: error: argument -f/--format: invalid choice: 'json' (choose from 'shell', 'table', 'value')```

Is there a json format plugin for the openstack client which I have to install?

**Comment by chilicat** [comment]
Never mind, I think its just a extremely old client version on my machine.

**Comment by chilicat** [comment]
Upgraded to Kilo clients provided by RDO:
python-neutronclient-2.4.0-1.el7.noarch
python-novaclient-2.23.0-1.el7.noarch
python-openstackclient-1.0.3-2.el7.noarch
python-keystoneclient-1.3.0-1.el7.noarch
python-cinderclient-1.2.1-1.el7.noarch
python-glanceclient-0.17.0-2.el7.noarch

doesn't support the json format.

**Comment by manasdk** [comment]
@chilicat Yeah likely that old client will not work. Lemme confirm which version of python-openstack client actually supports json.

**Comment by manasdk** [comment]
@chilicat I see support with 1.4.0 (likely 1.3.0 also does but due to oslo mismatches there are some issues running 1.3.0).

```
$openstack --version
openstack 1.4.0
```

```
$ openstack server create -h
usage: openstack server create [-h] [-f {html,json,shell,table,value,yaml}]
                               [-c COLUMN] [--max-width <integer>]
                               [--prefix PREFIX]
                               (--image <image> | --volume <volume>) --flavor
                               <flavor>
                               [--security-group <security-group-name>]
                               [--key-name <key-name>]
                               [--property <key=value>]
                               [--file <dest-filename=source-filename>]
                               [--user-data <user-data>]
                               [--availability-zone <zone-name>]
                               [--block-device-mapping <dev-name=mapping>]
                               [--nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid>]
                               [--hint <key=value>]
                               [--config-drive <config-drive-volume>|True]
                               [--min <count>] [--max <count>] [--wait]
                               <server-name>

Create a new server

positional arguments:
  <server-name>         New server name

optional arguments:
  -h, --help            show this help message and exit
  --image <image>       Create server from this image
  --volume <volume>     Create server from this volume
  --flavor <flavor>     Create server with this flavor
  --security-group <security-group-name>
                        Security group to assign to this server (repeat for
                        multiple groups)
  --key-name <key-name>
                        Keypair to inject into this server (optional
                        extension)
  --property <key=value>
                        Set a property on this server (repeat for multiple
                        values)
  --file <dest-filename=source-filename>
                        File to inject into image before boot (repeat for
                        multiple files)
  --user-data <user-data>
                        User data file to serve from the metadata server
  --availability-zone <zone-name>
                        Select an availability zone for the server
  --block-device-mapping <dev-name=mapping>
                        Map block devices; map is
                        <id>:<type>:<size(GB)>:<delete_on_terminate> (optional
                        extension)
  --nic <net-id=net-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,port-id=port-uuid>
                        Create a NIC on the server. Specify option multiple
                        times to create multiple NICs. Either net-id or port-
                        id must be provided, but not both. net-id: attach NIC
                        to network with this UUID, port-id: attach NIC to port
                        with this UUID, v4-fixed-ip: IPv4 fixed address for
                        NIC (optional), v6-fixed-ip: IPv6 fixed address for
                        NIC (optional).
  --hint <key=value>    Hints for the scheduler (optional extension)
  --config-drive <config-drive-volume>|True
                        Use specified volume as the config drive, or 'True' to
                        use an ephemeral drive
  --min <count>         Minimum number of servers to launch (default=1)
  --max <count>         Maximum number of servers to launch (default=1)
  --wait                Wait for build to complete

output formatters:
  output formatter options

  -f {html,json,shell,table,value,yaml}, --format {html,json,shell,table,value,yaml}
                        the output format, defaults to table
  -c COLUMN, --column COLUMN
                        specify the column(s) to include, can be repeated

table formatter:
  --max-width <integer>
                        Maximum display width, 0 to disable

shell formatter:
  a format a UNIX shell can parse (variable="value")

  --prefix PREFIX       add a prefix to all variable names
```

Looks like you are using `python-openstackclient-1.0.3-2.el7.noarch` and likely that back then there was no support for `json`. Is it possible for you to use a newer version?

**Comment by manasdk** [comment]
If upgrading to a newer unstable version of python-openstackclient is not an option then for a temporary solution would be switch back to https://github.com/StackStorm/st2contrib/tree/master/packs/openstack

Likely I can get python-openstackclient to support 1.0.4 (kilo) as well or if you are motivated then I can walk you through the process. Thoughts?

In anycase catch up with us on https://stackstorm.typeform.com/to/K76GRP for quicker turnaround :)

**Comment by Kami** [comment]
@manasdk I'm slightly confused about this issue.

Shouldn't the openstack client dependency be installed inside the virtualenv (as defined in requirements.txt) so system version shouldn't affect it since virtualenv one has precedence (we just need to make sure dependency specified in requirements.txt is pinned to a know working version).

**Comment by manasdk** [comment]
> Shouldn't the openstack client dependency be installed inside the virtualenv

Likely that https://github.com/StackStorm/openstack/blob/master/actions/src/lib/base.py#L36 means that the openstack client in the virtualenv is not actually used. I will probably have cycles next week to take a look at what might be going on.

**Comment by manasdk** [comment]
So on being prodded by Kami I decided to take a closer look as something did not exactly add up. Regardless of the system `python-openstackclient` StackStorm installs the right version from pip in a virtualenv - so what gives?

It turns out that the virtualenv binary is completely ignored as StackStorm does not update the PATH variable to include the `bin` directory of the virtual environment. So looks like we can fix some part of this in StackStorm proper. Once that is done the system `python-openstackclient` will be irrelevant.
