### ISSUE TITLE
Attachment support (slack.post_message)

### ISSUE THREAD

**Issue by pixelrebel** [StackStorm/st2contrib#301]
Are you planning on adding support for attachments?  I suppose this would make your action parameters pretty complex (i.e. introducing the attachments and fields arrays).

**Comment by armab** [comment]
There is [`st2-slack`](https://github.com/StackStorm/st2-slack/) repo, separated from `st2contrib` with attachments support, see: 
https://github.com/StackStorm/st2-slack/blob/master/actions/chat.postMessage.yaml#L9

You can try it.

(2 different slack packs is confusing, - we'll change that later).

**Comment by dzimine** [comment]
Let’s add a reference on /st2contrib/slack/README.md to this pack. Same with OpenStack…

**Comment by pixelrebel** [comment]
Great, I like the [`st2-slack`](https://github.com/StackStorm/st2-slack/) approach much better: a simple wrapper around the API, encompassing many commands.
