### ISSUE TITLE
[ansible] `become` privilege escalation issues

### ISSUE THREAD

**Issue by armab** [StackStorm/st2contrib#330]
Running Ansible via StackStorm pack with [privilege escalation options](http://docs.ansible.com/ansible/become.html) like [`become`](https://github.com/StackStorm/st2contrib/blob/2a6ead9b4a32f56425b8dc8c3d34bfa201e416fb/packs/ansible/actions/playbook.yaml#L32-L46)  doesn't work (?).

When running Ansible pack with command equivalent: 

```
Executed command "/opt/stackstorm/virtualenvs/ansible/bin/ansible-playbook --become-user=ubuntu --inventory-file=/home/ubuntu/configurations/ansible/hosts --become --become-method=su /home/ubuntu/configurations/ansible/staging.yml"
```

Ansible can't read `~/.ssh/config` of `ubuntu` user.

Reported by @vikrantpogula:

> Ansible playbook is not able to resolve the hostnames because my playbook uses hostnames from the ~/.ssh/config 
> Basically instead of saying <IP_ADDRESS> in my playbook i just use a Hostname which is then pointed to the actual servers ip address (using the config file)

**Comment by vikrantpogula** [comment]
Link for knowing about `ForwardAgent`. https://developer.github.com/guides/using-ssh-agent-forwarding/

This lets the ssh keys (like github) in the Host system's ssh-agent to be forwarded to the ssh-ed system. This eliminates adding ssh access keys to each target node

**Comment by LindsayHill** [comment]
Track here: https://github.com/StackStorm-Exchange/stackstorm-ansible/issues/16
