### ISSUE TITLE
Jira pack doesn't allow creation of custom issue type

### ISSUE THREAD

**Issue by psychopenguin** [StackStorm/st2contrib#359]
Jira pack alloes only the following issue types to be created:

- Task
- Story
- Epic
- Bug

I've created this issue to discuss the best way to make it to allow the creation of other types. I believe add other types to the action yaml is not good, because some places have custom types.

My idea is to totally remove the enum list from it, and make it a free string parameter. 

Or, alternatively, create a parameter like `custom_type` and it will override the default value for the issue type.

What do you guys think?

**Comment by manasdk** [comment]
> My idea is to totally remove the enum list from it, and make it a free string parameter.
Seems like the only reasonable solution.

I would only update the description to say that `task, story, bug and epic are typical types. Could also be custom_types.`

**Comment by psychopenguin** [comment]
hmm... let me see if i understood correcty: 

- remove the enum list
- update the description

Is this right? If so I will do the changes and create a PR. Thanks, @manasdk!

**Comment by manasdk** [comment]
@psychopenguin Yes you got it right.

:+1:
