### ISSUE TITLE
[question] Tests for packs

### ISSUE THREAD

**Issue by kuboj** [StackStorm/st2contrib#370]
Hello,

I was wondering - is there some reasonable way how to write test suites for different components of packs? It came to my mind when I was fixing AWS SQS sensor - the only way how to do it was to do it on whole StackStorm deployment

**Comment by jfryman** [comment]
@kuboj Take a look at https://docs.stackstorm.com/development/pack_testing.html

Does that give you what you need?

**Comment by kuboj** [comment]
Yeah, that looks exactly like what I wanted, thanks! BTW, is there some pack already included in ST2 that has well written tests so I can look into it? So for now luck while browsing the repos.

**Comment by Kami** [comment]
You can find some basic examples here:

* https://github.com/StackStorm/st2contrib/blob/master/packs/xml/tests/test_action_parse_xml.py
* https://github.com/StackStorm/st2contrib/blob/master/packs/circle_ci/tests/test_get_build_number_action.py
* https://github.com/StackStorm/st2contrib/blob/master/packs/docker/tests/test_sensor_docker_sensor.py

Keep in mind thought that senors are usually a bit harder to tests so you will probably need to use mock data and mock some methods.

I will close this ticket for now, but if you have any more questions, feel free to stop by on Slack / IRC - https://stackstorm.com/community/ :)
