### ISSUE TITLE
AWS aws.rds_get_list requires markers, params and action to be set

### ISSUE THREAD

**Issue by mward29** [StackStorm/st2contrib#381]
I suspect this is the case with several other AWS actions as well as I've seen it a fair amount.

In particular the aws.rds_get_list action requires markers, params and an action to be set before execution when it shouldn't. According to boto docs, it should only require access_key, secret and region which are all in config.yaml.

 Patrick suggested I submit this issue as he is looking into it.

**Comment by LindsayHill** [comment]
Tracking this against new repo location https://github.com/StackStorm-Exchange/stackstorm-aws/issues/40
