### ISSUE TITLE
AWS actions cannot handle non-string types

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2contrib#385]
boto3 method such as create_tags is expecting the tags to be a list of dicts. The current aws.ec2_create_tags expect the tags to be string. https://boto3.readthedocs.org/en/latest/reference/services/ec2.html?highlight=tag#EC2.Client.create_tags

**Comment by LindsayHill** [comment]
Lots of changes to AWS pack over last 18 months, don't think this is relevant any more.
