### ISSUE TITLE
AWS pack result marshalling should be generic

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2contrib#387]
Based on the conversation https://github.com/StackStorm/st2contrib/pull/386#discussion_r51978114 pack parser needs some updating.

Basically, write a generic marshaller from `boto.*` objects to `json`. Boto is not really meant for this purpose so it might be an interesting kludge.

**Comment by LindsayHill** [comment]
Lots of changes to AWS pack over last 18 months, don't think this is relevant any more.
