### ISSUE TITLE
Unable to authenticate from sensu server on stackstorm server.

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/st2contrib#391]
while doing the test command:
echo '{"foo":"bar"}' | ./st2_handler.py ./st2_handler.conf I get the following output:

root@i-nkorniyenko-CBC:/etc/sensu/handlers# echo '{"foo":"bar"}' | ./st2_handler.py ./st2_handler.conf
Cannot authenticate. Will try unauthed.Failed to register trigger type with st2.                 HTTP_CODE: 400
Failed registering with st2. Won't post event.
Traceback (most recent call last):
  File "./st2_handler.py", line 214, in <module>
    _register_with_st2()
  File "./st2_handler.py", line 137, in _register_with_st2
    _create_trigger_type()
  File "./st2_handler.py", line 98, in _create_trigger_type
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

==========================================================
SENSU box
==========================================================
pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
==========================================================
 pip -V
pip 8.0.2 from /usr/local/lib/python2.7/dist-packages/pip-8.0.2-py2.7.egg (python 2.7)
==========================================================

==========================================================
STACKSTORM BOX
==========================================================
pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
==========================================================
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
==========================================================

This version of the handler was used:
https://raw.githubusercontent.com/StackStorm/st2contrib/master/packs/sensu/etc/st2_handler.py

Any advice will be much appreciated!

**Comment by murgurgula** [comment]
st2 ('1.3.0.12',)

**Comment by manasdk** [comment]
Unable to reproduce

Proving that I have same code as upstream in `st2contrib`.
```
root@st2test:/etc/sensu/handlers# echo '{"client": {"name": 1}, "check":{"name": 2}, "id": "12345"}' | ./st2_handler.py ./st2_handler.conf
Sent sensu event to st2. HTTP_CODE:                 202
root@st2test:/etc/sensu/handlers#
root@st2test:/etc/sensu/handlers# cd /tmp
root@st2test:/tmp# wget https://raw.githubusercontent.com/StackStorm/st2contrib/b75f1a45a961ca7c48ce0dd6dd366bc29e24c7e6/packs/sensu/etc/st2_handler.py
--2016-02-08 15:32:59--  https://raw.githubusercontent.com/StackStorm/st2contrib/b75f1a45a961ca7c48ce0dd6dd366bc29e24c7e6/packs/sensu/etc/st2_handler.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.47.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.47.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6818 (6.7K) [text/plain]
Saving to: ‘st2_handler.py’

100%[==============================================================================================================================================================================================================================================>] 6,818       --.-K/s   in 0s

2016-02-08 15:33:00 (273 MB/s) - ‘st2_handler.py’ saved [6818/6818]

root@st2test:/tmp# diff st2_handler.py /etc/
Display all 189 possibilities? (y or n)
root@st2test:/tmp# diff st2_handler.py /etc/sensu/handlers/st2_handler.py
root@st2test:/tmp# cat /etc/sensu/handlers/st2_handler.conf | grep -v st2_password
---
st2_username: "admin"
st2_api_base_url: "https://127.0.0.1/v1"
st2_auth_base_url: "https://127.0.0.1"

sensu_host: 127.0.0.1
sensu_port: 4567
sensu_user: sensu
sensu_pass: ""
root@st2test:/tmp# grep backend /etc/st2/st2.conf
backend = pam
backend_kwargs =
```

Proves that handler did actually register the sensu event with StackStorm.
```
root@st2test:/etc/sensu/handlers# st2 trigger list | grep sensu
root@st2test:/etc/sensu/handlers# echo '{"client": {"name": 1}, "check":{"name": 2}, "id": "12345"}' | ./st2_handler.py ./st2_handler.conf
Registered trigger type with st2.
Sent sensu event to st2. HTTP_CODE:                 202
root@st2test:/etc/sensu/handlers# st2 trigger list | grep sensu
| sensu.event_handler                  | sensu | Trigger type for sensu event handler.
```

requests version on my local box
```
# pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires:
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by manasdk** [comment]
@murgurgula - Can you try and repro with the payload I used?

**Comment by lakshmi-kannan** [comment]
1. Fix default config file to not use ports and use https by default
https://github.com/StackStorm/st2contrib/blob/master/packs/sensu/etc/st2_handler.conf#L4

2. In all except blocks in the code, add a traceback.print_exc() so error messages are more explicit.
