### ISSUE TITLE
st2.list_executions

### ISSUE THREAD

**Issue by emedvedev** [StackStorm/st2contrib#394]
While polishing https://github.com/StackStorm/st2contrib/pull/329, I noticed that `st2.list_executions` becomes unusable when used a few times in a row: it includes every execution's result in the output and grows with every subsequent request.

There's no way to exclude executions' content right now (or I just don't see one), so getting a list of 10 large executions will just hang st2. We should probably have a way to exclude content, because with lists you just want metadata in most cases.

@enykeev really likes to see the world burn, so he proposed to remove the action and corresponding alias, but I think we can find a better way :stuck_out_tongue:

**Comment by Kami** [comment]
IIRC, we had some code in the past to exclude the result of `list_executions` executions in this action result, but not exactly sure what happened to it.
