### ISSUE TITLE
CentOS7: st2.actions.list fails on a weird SSL error. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2contrib#417]
Details here: 
https://gist.github.com/lmarty/97ea65f5c228e2465f2e

See IRC for debugging info. 

Related: http://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

OS: Cent OS 7
st2 version: Unknown

**Comment by lmarty** [comment]
st2 version  = 1.3.2

**Comment by emptywee** [comment]
Cannot reproduce here on CentOS7.
```
$ rpm -qa | grep openssl
openssl-1.0.1e-51.el7_2.2.x86_64
openssl-libs-1.0.1e-51.el7_2.2.x86_64
openssl-devel-1.0.1e-51.el7_2.2.x86_64
```
requests module:
```
$ pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python2.7/site-packages
Requires:
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
nginx:
```
nginx-1.8.1-1.el7.ngx.x86_64
```

debug run:
```
$ st2 --debug run st2.actions.list
# -------- begin 54326352 request ----------
curl -X POST -H  'Content-Length: 2' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' -H  'Connection: keep-alive' -H  'content-type: application/json' -H  'Authorization: Basic ...' --data-binary '{}' https://st2.stack.qadev.corp/auth/tokens
# -------- begin 54326352 response ----------
{"user": "ansible", "token": "d...3", "expiry": "2016-02-27T19:37:36.700969Z", "id": "5...7", "metadata": {}}
# -------- end 54326352 response ------------

2016-02-26 19:37:36,716  DEBUG - Token has been cached in "/home/ansible/.st2/token-ansible"
# -------- begin 54312144 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: d...3' https://st2.stack.qadev.corp/api/actions/st2.actions.list
# -------- begin 54312144 response ----------
{"name": "actions.list", "parameters": {"limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "tags": [], "description": "Retrieve a list of available StackStorm actions.", "enabled": true, "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "pack": "st2", "ref": "st2.actions.list", "id": "566748618e326f19361c7ca7", "runner_type": "run-python"}
# -------- end 54312144 response ------------

# -------- begin 54312016 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: d...3' 'https://st2.stack.qadev.corp/api/runnertypes/?name=run-python'
# -------- begin 54312016 response ----------
[{"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}, "timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, "id": "566748568e326f19361c7aab", "name": "run-python"}]
# -------- end 54312016 response ------------

# -------- begin 54312528 request ----------
curl -X POST -H  'Content-Length: 48' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' -H  'Connection: keep-alive' -H  'X-Auth-Token: d...3' -H  'content-type: application/json' --data-binary '{"action": "st2.actions.list", "parameters": {}}' https://st2.stack.qadev.corp/api/executions
# -------- begin 54312528 response ----------
{"status": "requested", "start_timestamp": "2016-02-26T19:37:36.943771Z", "runner": {"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}, "env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}}, "id": "566748568e326f19361c7aab", "name": "run-python"}, "context": {"user": "ansible"}, "action": {"name": "actions.list", "runner_type": "run-python", "tags": [], "enabled": true, "pack": "st2", "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "parameters": {"limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "ref": "st2.actions.list", "id": "566748618e326f19361c7ca7", "description": "Retrieve a list of available StackStorm actions."}, "liveaction": {"action": "st2.actions.list", "callback": {}, "runner_info": {}, "id": "56d0a9808e326f0b029484d2", "parameters": {}}, "id": "56d0a9808e326f0b029484d3"}
# -------- end 54312528 response ------------

.# -------- begin 54312528 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: d...3' https://st2.stack.qadev.corp/api/executions/56d0a9808e326f0b029484d3
# -------- begin 54312528 response ----------
{"status": "succeeded", "start_timestamp": "2016-02-26T19:37:36.943771Z", "runner": {"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}, "env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}}, "id": "566748568e326f19361c7aab", "name": "run-python"}, "result": {"result": [{"description": "Run ad-hoc ansible command (module)", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible.py", "notify": {}, "uid": "action:ansible:command", "pack": "ansible", "ref": "ansible.command", "id": "566748608e326f19361c7c7a", "name": "command"}, {"description": "Run ad-hoc ansible command (module) on local machine", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible.py", "notify": {}, "uid": "action:ansible:command_local", "pack": "ansible", "ref": "ansible.command_local", "id": "566748608e326f19361c7c7b", "name": "command_local"}, {"description": "Download & Install role from ansible galaxy", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible_galaxy.py", "notify": {}, "uid": "action:ansible:galaxy.install", "pack": "ansible", "ref": "ansible.galaxy.install", "id": "566748608e326f19361c7c7c", "name": "galaxy.install"}, {"description": "Display a list of installed roles from ansible galaxy", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible_galaxy.py", "notify": {}, "uid": "action:ansible:galaxy.list", "pack": "ansible", "ref": "ansible.galaxy.list", "id": "566748608e326f19361c7c7d", "name": "galaxy.list"}, {"description": "Remove an installed from ansible galaxy role", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible_galaxy.py", "notify": {}, "uid": "action:ansible:galaxy.remove", "pack": "ansible", "ref": "ansible.galaxy.remove", "id": "566748608e326f19361c7c7e", "name": "galaxy.remove"}, {"description": "Run ansible playbook", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible_playbook.py", "notify": {}, "uid": "action:ansible:playbook", "pack": "ansible", "ref": "ansible.playbook", "id": "566748608e326f19361c7c7f", "name": "playbook"}, {"description": "Decrypt ansible data files", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible_vault.py", "notify": {}, "uid": "action:ansible:vault.decrypt", "pack": "ansible", "ref": "ansible.vault.decrypt", "id": "566748608e326f19361c7c80", "name": "vault.decrypt"}, {"description": "Encrypt ansible data files", "runner_type": "local-shell-script", "tags": [], "enabled": true, "entry_point": "ansible_vault.py", "notify": {}, "uid": "action:ansible:vault.encrypt", "pack": "ansible", "ref": "ansible.vault.encrypt", "id": "566748608e326f19361c7c81", "name": "vault.encrypt"}, {"description": "Format an execution result for chatops", "runner_type": "run-python", "tags": [], "enabled": true, "entry_point": "format_execution_result.py", "notify": {}, "uid": "action:chatops:format_execution_result", "pack": "chatops", "ref": "chatops.format_execution_result", "id": "569f946b8e326f7de6826fb2", "name": "format_execution_result"}, {"uid": "action:chatops:format_result", "runner_type": "run-python", "tags": [], "enabled": true, "name": "format_result", "entry_point": "format_result.py", "pack": "chatops", "ref": "chatops.format_result", "id": "566748668e326f19361c7d8b", "description": "Format an execution result for chatops"}], "exit_code": 0, "stderr": "st2.actions.python.St2ActionsListAction: DEBUG    Calling client method \"get_all\" with kwargs \"{'limit': 10}\"\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\n", "stdout": ""}, "context": {"user": "ansible"}, "action": {"runner_type": "run-python", "name": "actions.list", "parameters": {"limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "tags": [], "enabled": true, "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "pack": "st2", "ref": "st2.actions.list", "id": "566748618e326f19361c7ca7", "description": "Retrieve a list of available StackStorm actions."}, "liveaction": {"action": "st2.actions.list", "callback": {}, "runner_info": {"hostname": "st2.stack.qadev.corp", "pid": 2500}, "id": "56d0a9808e326f0b029484d2", "parameters": {}}, "id": "56d0a9808e326f0b029484d3", "end_timestamp": "2016-02-26T19:37:38.344278Z"}
# -------- end 54312528 response ------------


id: 56d0a9808e326f0b029484d3
status: succeeded
parameters: None
result:
  exit_code: 0
  result:
  - description: Run ad-hoc ansible command (module)
    enabled: true
    entry_point: ansible.py
    id: 566748608e326f19361c7c7a
    name: command
    notify: {}
    pack: ansible
    ref: ansible.command
    runner_type: local-shell-script
    tags: []
    uid: action:ansible:command
...
```

**Comment by lmarty** [comment]
Only diff I see between our environments here is the nginx version.  Output below.

[root@ip-10-48-107-24 st2]# rpm -qa | grep openssl
openssl-devel-1.0.1e-51.el7_2.2.x86_64
openssl-libs-1.0.1e-51.el7_2.2.x86_64
openssl-1.0.1e-51.el7_2.2.x86_64
[root@ip-10-48-107-24 st2]# pip show requests
You are using pip version 7.1.0, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python2.7/site-packages
Requires:
[root@ip-10-48-107-24 st2]# rpm -qa | grep nginx
nginx-filesystem-1.6.3-8.el7.noarch
nginx-1.6.3-8.el7.x86_64
[root@ip-10-48-107-24 st2]# st2 --debug run st2.actions.list
# -------- begin 48995216 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: 4b6ed5a960f54fddad82260d87d5be64' http://127.0.0.1:9101/v1/actions/st2.actions.list
# -------- begin 48995216 response ----------
{"name": "actions.list", "parameters": {"exclude": {"default": ["parameters", "notify"], "type": "array", "description": "List of attributes to exclude"}, "limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "tags": [], "description": "Retrieve a list of available StackStorm actions.", "enabled": true, "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "pack": "st2", "ref": "st2.actions.list", "id": "56cbaeaee5d38d17a91b519e", "runner_type": "run-python"}
# -------- end 48995216 response ------------

# -------- begin 48995792 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: 4b6ed5a960f54fddad82260d87d5be64' 'http://127.0.0.1:9101/v1/runnertypes/?name=run-python'
# -------- begin 48995792 response ----------
[{"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}, "timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, "id": "56cb99b5e5d38d1e7e9f4c52", "name": "run-python"}]
# -------- end 48995792 response ------------

# -------- begin 48994640 request ----------
curl -X POST -H  'Content-Length: 48' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' -H  'Connection: keep-alive' -H  'X-Auth-Token: 4b6ed5a960f54fddad82260d87d5be64' -H  'content-type: application/json' --data-binary '{"action": "st2.actions.list", "parameters": {}}' http://127.0.0.1:9101/v1/executions
# -------- begin 48994640 response ----------
{"status": "requested", "start_timestamp": "2016-02-26T19:44:33.181255Z", "runner": {"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}, "env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}}, "id": "56cb99b5e5d38d1e7e9f4c52", "name": "run-python"}, "context": {"user": "test"}, "action": {"name": "actions.list", "runner_type": "run-python", "tags": [], "enabled": true, "pack": "st2", "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "parameters": {"exclude": {"default": ["parameters", "notify"], "type": "array", "description": "List of attributes to exclude"}, "limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "ref": "st2.actions.list", "id": "56cbaeaee5d38d17a91b519e", "description": "Retrieve a list of available StackStorm actions."}, "liveaction": {"action": "st2.actions.list", "callback": {}, "runner_info": {}, "id": "56d0ab21e5d38d0e40e37414", "parameters": {}}, "id": "56d0ab21e5d38d0e40e37415"}
# -------- end 48994640 response ------------

.# -------- begin 48994640 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: 4b6ed5a960f54fddad82260d87d5be64' http://127.0.0.1:9101/v1/executions/56d0ab21e5d38d0e40e37415
# -------- begin 48994640 response ----------
{"status": "running", "start_timestamp": "2016-02-26T19:44:33.181255Z", "runner": {"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}, "env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}}, "id": "56cb99b5e5d38d1e7e9f4c52", "name": "run-python"}, "context": {"user": "test"}, "action": {"runner_type": "run-python", "name": "actions.list", "parameters": {"exclude": {"default": ["parameters", "notify"], "type": "array", "description": "List of attributes to exclude"}, "limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "tags": [], "enabled": true, "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "pack": "st2", "ref": "st2.actions.list", "id": "56cbaeaee5d38d17a91b519e", "description": "Retrieve a list of available StackStorm actions."}, "liveaction": {"action": "st2.actions.list", "callback": {}, "runner_info": {"hostname": "ip-10-48-107-24.us-west-2.compute.internal", "pid": 3462}, "id": "56d0ab21e5d38d0e40e37414", "parameters": {}}, "id": "56d0ab21e5d38d0e40e37415"}
# -------- end 48994640 response ------------

.# -------- begin 48994640 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: 4b6ed5a960f54fddad82260d87d5be64' http://127.0.0.1:9101/v1/executions/56d0ab21e5d38d0e40e37415
# -------- begin 48994640 response ----------
{"status": "failed", "start_timestamp": "2016-02-26T19:44:33.181255Z", "runner": {"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}, "env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}}, "id": "56cb99b5e5d38d1e7e9f4c52", "name": "run-python"}, "result": {"result": null, "exit_code": 1, "stderr": "st2.actions.python.St2ActionsListAction: DEBUG    Calling client method \"get_all\" with kwargs \"{'limit': 10}\"\nTraceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 116, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 61, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/st2/actions/actions_list.py\", line 27, in run\n    'exclude_attributes': exclude\n  File \"/opt/stackstorm/packs/st2/actions/lib/action.py\", line 86, in _run_client_method\n    result = method(**method_kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 35, in decorate\n    return func(*args, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py\", line 187, in get_all\n    response = self.client.get(url=url, params=params, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py\", line 33, in decorate\n    return func(*args, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py\", line 44, in decorate\n    return func(*args, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py\", line 68, in get\n    response = requests.get(self.root + url, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py\", line 67, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py\", line 53, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py\", line 468, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py\", line 576, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py\", line 447, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:765)\n", "stdout": ""}, "context": {"user": "test"}, "action": {"runner_type": "run-python", "name": "actions.list", "parameters": {"exclude": {"default": ["parameters", "notify"], "type": "array", "description": "List of attributes to exclude"}, "limit": {"default": 10, "required": false, "type": "integer", "description": "Maximum number of actions to return"}, "pack": {"required": false, "type": "string", "description": "Optional pack to filter on"}}, "tags": [], "enabled": true, "entry_point": "actions_list.py", "notify": {}, "uid": "action:st2:actions.list", "pack": "st2", "ref": "st2.actions.list", "id": "56cbaeaee5d38d17a91b519e", "description": "Retrieve a list of available StackStorm actions."}, "liveaction": {"action": "st2.actions.list", "callback": {}, "runner_info": {"hostname": "ip-10-48-107-24.us-west-2.compute.internal", "pid": 3462}, "id": "56d0ab21e5d38d0e40e37414", "parameters": {}}, "id": "56d0ab21e5d38d0e40e37415", "end_timestamp": "2016-02-26T19:44:35.737180Z"}
# -------- end 48994640 response ------------


id: 56d0ab21e5d38d0e40e37415
status: failed
parameters: None
result:
  exit_code: 1
  result: null
  stderr: "st2.actions.python.St2ActionsListAction: DEBUG    Calling client method "get_all" with kwargs "{'limit': 10}"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/st2/actions/actions_list.py", line 27, in run
    'exclude_attributes': exclude
  File "/opt/stackstorm/packs/st2/actions/lib/action.py", line 86, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 35, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 187, in get_all
    response = self.client.get(url=url, params=params, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 33, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 68, in get
    response = requests.get(self.root + url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:765)
"
  stdout: ''
[root@ip-10-48-107-24 st2]#

**Comment by emptywee** [comment]
Feels like st2.actions.list expects SSL but connects to plain HTTP port. Need to debug what URL the action makes requests to.

**Comment by lakshmi-kannan** [comment]
@lmarty: I have the exact versions you have and I can't repro. 

```
[vagrant@centos7 ~]$ rpm -qa | grep openssl
openssl-libs-1.0.1e-51.el7_2.2.x86_64
openssl-1.0.1e-51.el7_2.2.x86_64
openssl-devel-1.0.1e-51.el7_2.2.x86_64
[vagrant@centos7 ~]$

[vagrant@centos7 ~]$ st2 run st2.actions.list limit=10
.
id: 56d0d17c2cbdfd120d566978
status: succeeded
parameters:
  limit: 10

[vagrant@centos7 ~]$ /opt/stackstorm/st2/bin/pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /opt/stackstorm/st2/lib/python2.7/site-packages
Requires:

[vagrant@centos7 ~]$ rpm -qa | grep nginx
nginx-1.6.3-8.el7.x86_64
nginx-filesystem-1.6.3-8.el7.noarch
[vagrant@centos7 ~]$

```

@emptywee has an excellent point about http vs https. I see all your curl requests indicate request should be made to http but somehow we also see SSL error. 

Can you dump the contents of ~root/.st2/config and mask any credentials?

**Comment by lmarty** [comment]
Got this one figured out with your guidance.  Updated all refs to the api and auth urls in the bot script, st2.conf and config.js to use https, did a st2ctl reload --register-all and things started flowing.  Thanks for the help!
