### ISSUE TITLE
sensu.unsilence client passed as argument instead of check.

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/st2contrib#419]
When using sensu.unsilence on a specific check, the client is passed as check argument.

Fix:

`path = "%s/%s" % (path, args.client)` ===> `path = "%s/%s" % (path, args.check)`

 `#!/usr/bin/python

from lib import sensu
import argparse

parser = argparse.ArgumentParser(description='Sensu Unsilence Actions')

parser.add_argument('--client', nargs='?', required=True)
parser.add_argument('--check', nargs='?', default=False)
args = parser.parse_args()

stashes = sensu.Stashes('config.yaml')

path = "silence/%s" % args.client
if args.check:
    path = "%s/%s" % (path, args.check)

print(stashes.delete(path))
`

**Comment by Kami** [comment]
Thanks.

Pushed a fix in https://github.com/StackStorm/st2contrib/commit/c182d3bb832abe9f96ed8f1c043e841046b922ed.

Next time, as I mentioned on Slack, feel free to open a PR with the fix yourself.
