### ISSUE TITLE
Google pack: `get_search_results` is broken

### ISSUE THREAD

**Issue by emedvedev** [StackStorm/st2contrib#437]
Reported by @runseb, verified. `get_search_results` always returns an empty list.

**Comment by Kami** [comment]
IIRC, that library relies on scraping data directly from HTML so it probably means that the underlying library needs to be updated.

**Comment by Kami** [comment]
Alright, I pushed a fix for this to our upstream library fork.

I will close this issue for now, but it's worth noting that the upstream library relies on parsing the generated HTML which means it's very fragile and it could break at any time Google changes their HTML.

**Comment by emedvedev** [comment]
Great that it's working now! 

Parsing the HTML is flaky, but the search API has been deprecated, IIRC, so I don't think there's a much better solution. Not one we should spend time on right now, anyway.

**Comment by Kami** [comment]
Also, to fix it you need to run `st2 pack.setup_virtualenv packs=google` so that the dependency is updated.

**Comment by runseb** [comment]
it is worth keeping in mind that quite a few of your chats examples use that pack.
