### ISSUE TITLE
Failed to download pack 

### ISSUE THREAD

**Issue by jsenon** [StackStorm/st2contrib#476]
Hello,

How to configure stackstorm, to perform pack installation on CLI behind an HTTP/HTTPS Proxy `st2 run packs.download packs=docker`
?
When I made export http_proxy or HTTP_PROXY, we are unable to connect to github repository.
OS=RedHat6

Thanks

**Comment by manasdk** [comment]
@jsenon Will need a bit of trial and error to figure this out.

I believe the library we use to perform git clone uses system git. Therefore, it should be possible to set the git config via `git config --global http.proxy <proxy_url>` This command would have to be run at the `st2` user since the actual action is executed by that user on the StackStorm box.

**Comment by jsenon** [comment]
Hello @manasdk 

I'll try git config proxy on st2 user, Thanks. Nevertheless find log bellow.
I've set : 

- export http_proxy="http://foo:3128"

- export https_proxy="http://foo.3128"

- export no_proxy="localhost,127.0.0.1,127.0.0.0/8"


`[root@fr0-vsiaas-2348 ~]# st2 --debug run packs.install packs=docker repo_url=https://github.com/StackStorm/st2contrib.git
# -------- begin 140366354801424 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' http://127.0.0.1:9101/v1/actions/packs.install
# -------- begin 140366354801424 response ----------
{"name": "install", "parameters": {"packs": {"items": {"type": "string"}, "required": true, "type": "array"}, "repo_url": {"default": "StackStorm/st2contrib", "type": "string"}, "env": {"required": false, "type": "object", "description": "Optional environment variables"}, "register": {"default": "actions,aliases,sensors", "type": "string", "description": "Possible options are all, sensors, actions, rules, aliases."}, "subtree": {"default": false, "type": "boolean", "description": "Set to true if packs are located in a packs/ directory and not in the repository root"}, "branch": {"default": "master", "type": "string"}}, "tags": [], "description": "Installs packs from st2-contrib into local content repository. Will download pack, load the actions, sensors and rules from the pack. Note that install require reboot of some st2 services.", "enabled": true, "entry_point": "workflows/install.yaml", "notify": {}, "uid": "action:packs:install", "pack": "packs", "ref": "packs.install", "id": "570df6cb2e67055776793e32", "runner_type": "action-chain"}
# -------- end 140366354801424 response ------------
 
# -------- begin 140366354801296 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' 'http://127.0.0.1:9101/v1/runnertypes/?name=action-chain'
# -------- begin 140366354801296 response ----------
[{"runner_module": "st2actions.runners.actionchainrunner", "description": "A runner for launching linear action chains.", "enabled": true, "runner_parameters": {"skip_notify": {"default": [], "type": "array", "description": "List of tasks to skip notifications for."}, "display_published": {"default": false, "type": "boolean", "description": "Intermediate published variables will be stored and displayed."}}, "id": "570df6c92e67055776793e08", "name": "action-chain"}]
# -------- end 140366354801296 response ------------
 
# -------- begin 140366354801808 request ----------
curl -X POST -H  'Content-Length: 124' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' -H  'Connection: keep-alive' -H  'content-type: application/json' --data-binary '{"action": "packs.install", "parameters": {"repo_url": "https://github.com/StackStorm/st2contrib.git", "packs": ["docker"]}}' http://127.0.0.1:9101/v1/executions
# -------- begin 140366354801808 response ----------
{"status": "requested", "start_timestamp": "2016-04-14T16:08:32.576543Z", "parameters": {"repo_url": "https://github.com/StackStorm/st2contrib.git", "packs": ["docker"]}, "runner": {"runner_module": "st2actions.runners.actionchainrunner", "description": "A runner for launching linear action chains.", "enabled": true, "runner_parameters": {"skip_notify": {"default": [], "type": "array", "description": "List of tasks to skip notifications for."}, "display_published": {"default": false, "type": "boolean", "description": "Intermediate published variables will be stored and displayed."}}, "id": "570df6c92e67055776793e08", "name": "action-chain"}, "context": {"user": "stanley"}, "action": {"name": "install", "runner_type": "action-chain", "tags": [], "enabled": true, "pack": "packs", "entry_point": "workflows/install.yaml", "notify": {}, "uid": "action:packs:install", "parameters": {"env": {"required": false, "type": "object", "description": "Optional environment variables"}, "packs": {"items": {"type": "string"}, "required": true, "type": "array"}, "register": {"default": "actions,aliases,sensors", "type": "string", "description": "Possible options are all, sensors, actions, rules, aliases."}, "repo_url": {"default": "StackStorm/st2contrib", "type": "string"}, "subtree": {"default": false, "type": "boolean", "description": "Set to true if packs are located in a packs/ directory and not in the repository root"}, "branch": {"default": "master", "type": "string"}}, "ref": "packs.install", "id": "570df6cb2e67055776793e32", "description": "Installs packs from st2-contrib into local content repository. Will download pack, load the actions, sensors and rules from the pack. Note that install require reboot of some st2 services."}, "liveaction": {"action": "packs.install", "callback": {}, "runner_info": {}, "id": "570fc0802e6705671e2afd01", "parameters": {"repo_url": "https://github.com/StackStorm/st2contrib.git", "packs": ["docker"]}}, "id": "570fc0802e6705671e2afd02"}
# -------- end 140366354801808 response ------------
 
.# -------- begin 140366354801808 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' http://127.0.0.1:9101/v1/executions/570fc0802e6705671e2afd02
# -------- begin 140366354801808 response ----------
{"status": "failed", "start_timestamp": "2016-04-14T16:08:32.576543Z", "parameters": {"repo_url": "https://github.com/StackStorm/st2contrib.git", "packs": ["docker"]}, "runner": {"runner_module": "st2actions.runners.actionchainrunner", "description": "A runner for launching linear action chains.", "enabled": true, "runner_parameters": {"skip_notify": {"default": [], "type": "array", "description": "List of tasks to skip notifications for."}, "display_published": {"default": false, "type": "boolean", "description": "Intermediate published variables will be stored and displayed."}}, "id": "570df6c92e67055776793e08", "name": "action-chain"}, "id": "570fc0802e6705671e2afd02", "result": {"tasks": [{"name": "download", "workflow": null, "created_at": "2016-04-14T16:08:32.871435+00:00", "updated_at": "2016-04-14T16:08:34.036987+00:00", "state": "failed", "result": {"exit_code": 1, "result": null, "stderr": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 116, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 61, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py\", line 91, in run\n    branch=branch)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py\", line 120, in _clone_repo\n    Repo.clone_from(repo_url, abs_local_path, branch=branch, depth=1)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py\", line 743, in clone_from\n    return cls._clone(Git(os.getcwd()), url, to_path, GitCmdObjectDB, progress, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py\", line 695, in _clone\n    finalize_process(proc)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/util.py\", line 132, in finalize_process\n    proc.wait()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py\", line 112, in wait\n    raise GitCommandError(self.args, status, self.proc.stderr.read())\ngit.exc.GitCommandError: 'git clone --depth=1 --branch=master -v https://github.com/StackStorm/st2contrib.git /root/st2contrib' returned exit status 128: error: Couldn't resolve host 'github.com' while accessing https://github.com/StackStorm/st2contrib.git/info/refs\n\nfatal: HTTP request failed\n\n", "stdout": ""}, "id": "download", "execution_id": "570fc0802e67056056e01e21"}]}, "context": {"user": "stanley"}, "action": {"runner_type": "action-chain", "name": "install", "parameters": {"env": {"required": false, "type": "object", "description": "Optional environment variables"}, "packs": {"items": {"type": "string"}, "required": true, "type": "array"}, "register": {"default": "actions,aliases,sensors", "type": "string", "description": "Possible options are all, sensors, actions, rules, aliases."}, "repo_url": {"default": "StackStorm/st2contrib", "type": "string"}, "subtree": {"default": false, "type": "boolean", "description": "Set to true if packs are located in a packs/ directory and not in the repository root"}, "branch": {"default": "master", "type": "string"}}, "tags": [], "enabled": true, "entry_point": "workflows/install.yaml", "notify": {}, "uid": "action:packs:install", "pack": "packs", "ref": "packs.install", "id": "570df6cb2e67055776793e32", "description": "Installs packs from st2-contrib into local content repository. Will download pack, load the actions, sensors and rules from the pack. Note that install require reboot of some st2 services."}, "liveaction": {"action": "packs.install", "callback": {}, "runner_info": {"hostname": "fr0-vsiaas-2348", "pid": 24662}, "id": "570fc0802e6705671e2afd01", "parameters": {"repo_url": "https://github.com/StackStorm/st2contrib.git", "packs": ["docker"]}}, "children": ["570fc0802e67056056e01e21"], "end_timestamp": "2016-04-14T16:08:34.074509Z"}
# -------- end 140366354801808 response ------------
 
 
# -------- begin 140366354801808 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.9.1' 'http://127.0.0.1:9101/v1/executions/570fc0802e6705671e2afd02/children/?depth=-1'
# -------- begin 140366354801808 response ----------
[{"status": "failed", "start_timestamp": "2016-04-14T16:08:32.892994Z", "parent": "570fc0802e6705671e2afd02", "parameters": {"packs": ["docker"], "subtree": false, "repo_url": "https://github.com/StackStorm/st2contrib.git", "branch": "master"}, "runner": {"runner_module": "st2actions.runners.pythonrunner", "description": "A runner for launching python actions.", "enabled": true, "runner_parameters": {"timeout": {"default": 600, "type": "integer", "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}, "env": {"type": "object", "description": "Environment variables which will be available to the script(e.g. key1=val1,key2=val2)"}}, "id": "570df6c92e67055776793e09", "name": "python-script"}, "result": {"result": null, "exit_code": 1, "stderr": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 116, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 61, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py\", line 91, in run\n    branch=branch)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py\", line 120, in _clone_repo\n    Repo.clone_from(repo_url, abs_local_path, branch=branch, depth=1)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py\", line 743, in clone_from\n    return cls._clone(Git(os.getcwd()), url, to_path, GitCmdObjectDB, progress, **kwargs)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py\", line 695, in _clone\n    finalize_process(proc)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/util.py\", line 132, in finalize_process\n    proc.wait()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py\", line 112, in wait\n    raise GitCommandError(self.args, status, self.proc.stderr.read())\ngit.exc.GitCommandError: 'git clone --depth=1 --branch=master -v https://github.com/StackStorm/st2contrib.git /root/st2contrib' returned exit status 128: error: Couldn't resolve host 'github.com' while accessing https://github.com/StackStorm/st2contrib.git/info/refs\n\nfatal: HTTP request failed\n\n", "stdout": ""}, "context": {"parent": {"user": "stanley", "execution_id": "570fc0802e6705671e2afd02"}, "chain": {"name": "download", "parameters": {"repo_url": "{{repo_url}}", "subtree": "{{subtree}}", "branch": "{{branch}}", "packs": "{{packs}}"}, "publish": null, "params": null, "notify": null, "on_failure": null, "ref": "packs.download", "on_success": "virtualenv_prerun"}, "user": "stanley"}, "action": {"runner_type": "python-script", "name": "download", "parameters": {"branch": {"default": "master", "type": "string"}, "packs": {"items": {"type": "string"}, "type": "array"}, "abs_repo_base": {"default": "/opt/stackstorm/packs/", "type": "string", "immutable": true}, "subtree": {"default": false, "type": "boolean"}, "repo_url": {"default": "StackStorm/st2contrib", "type": "string"}, "verifyssl": {"default": true, "type": "boolean"}}, "tags": [], "enabled": true, "entry_point": "pack_mgmt/download.py", "notify": {}, "uid": "action:packs:download", "pack": "packs", "ref": "packs.download", "id": "570df6cb2e67055776793e30", "description": "Downloads packs and places it in the local content repository."}, "liveaction": {"action": "packs.download", "callback": {}, "runner_info": {"hostname": "fr0-vsiaas-2348", "pid": 24683}, "id": "570fc0802e67056056e01e20", "parameters": {"branch": "master", "subtree": false, "repo_url": "https://github.com/StackStorm/st2contrib.git", "packs": ["docker"]}}, "id": "570fc0802e67056056e01e21", "end_timestamp": "2016-04-14T16:08:33.960569Z"}]
# -------- end 140366354801808 response ------------
 
id: 570fc0802e6705671e2afd02
action.ref: packs.install
parameters:
  packs:
  - docker
  repo_url: https://github.com/StackStorm/st2contrib.git
status: failed
error: Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 91, in run
    branch=branch)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 120, in _clone_repo
    Repo.clone_from(repo_url, abs_local_path, branch=branch, depth=1)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py", line 743, in clone_from
    return cls._clone(Git(os.getcwd()), url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py", line 695, in _clone
    finalize_process(proc)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/util.py", line 132, in finalize_process
    proc.wait()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 112, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
git.exc.GitCommandError: 'git clone --depth=1 --branch=master -v https://github.com/StackStorm/st2contrib.git /root/st2contrib' returned exit status 128: error: Couldn't resolve host 'github.com' while accessing https://github.com/StackStorm/st2contrib.git/info/refs
 
fatal: HTTP request failed
 
 
traceback: None
failed_on: download
start_timestamp: 2016-04-14T16:08:32.576543Z
end_timestamp: 2016-04-14T16:08:34.074509Z
+--------------------------+--------+----------+----------------+-------------------------------+
| id                       | status | task     | action         | start_timestamp               |
+--------------------------+--------+----------+----------------+-------------------------------+
| 570fc0802e67056056e01e21 | failed | download | packs.download | Thu, 14 Apr 2016 16:08:32 UTC |
+--------------------------+--------+----------+----------------+-------------------------------+
 `

**Comment by manasdk** [comment]
Which box did you setup those environment variables on? The actual git command is executed on a an actionrunner box so it would need to be on those boxes.

**Comment by jsenon** [comment]
Don't really understand the question. What do you mean by box? I've installed through 
https://docs.stackstorm.com/install/rhel6.html
Do I have to configure environment for "stanley" user?
It's this command who failed with http proxy error : `st2 run packs.download packs=docker`

**Comment by manasdk** [comment]
> It's this command who failed with http proxy error : st2 run packs.download packs=docker

True. However, this is the CLI i.e. the actual failure is not in the session where the `st2` cli executes. The error actually is in the environment of the `st2actionrunner` process. If you export HTTP_PROXY in the shell where you run the action `st2 run packs.download packs=docker` then that environment variable is only available locally in that shell and sent across the stackstorm API (st2api) to an action runner (st2actionrunner).

Try these steps on the box (VM etc) where StackStorm is installed -

```
$ sudo su
$ git config --global http.proxy <proxy_url>
$ st2 run packs.download packs=docker
```

Again I would try these out locally but I do not have an http proxy in our local environment.

**Comment by jsenon** [comment]
That's work. Thanks a lot @manasdk

**Comment by Kami** [comment]
@manasdk We should add some kind of section on configuring and using HTTP proxy with StackStorm to our documentation...

**Comment by LindsayHill** [comment]
Closing old issue - we now have docs on using a proxy - https://docs.stackstorm.com/reference/proxy.html
