### ISSUE TITLE
Jira extra_fields does not seem to allow the assignee field

### ISSUE THREAD

**Issue by jennyfountain** [StackStorm/st2contrib#480]
I added the assignee field and it still created the ticket unassigned.  

Here is what I added to the extra_fields:

{
 "assignee": {
   "name": "jfountain"
 }
}

**Comment by jennyfountain** [comment]
Am I doing something wrong?

**Comment by lakshmi-kannan** [comment]
@jennyfountain I replied on slack but here it is anyways -

Unfortunately, the client library and APIs are not well thought out. There is another method you have to call if you want to assign the issue.  https://github.com/pycontribs/jira/blob/develop/jira/client.py#L923, It looks like there are two APIs - 1. Create issue - https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-create-issue 2. Assign issue via create meta API - https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-edit-issues
Now, they can be combined into a single action or a workflow. Do you want to take a stab at fixing it?

**Comment by jennyfountain** [comment]
Yeah! I will work on it! Thank you!

**Comment by LindsayHill** [comment]
Track here: https://github.com/StackStorm-Exchange/stackstorm-jira/issues/8
