### ISSUE TITLE
Move pack linting etc out of st2contrib to make it shareable

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2contrib#500]
Not just the lint-configs but also Makefile + specific work scripts which add massive value. Specifically `https://github.com/StackStorm/st2contrib/tree/master/scripts` and `https://github.com/StackStorm/st2contrib/blob/master/Makefile` would be helpful in multiple repos.

/cc @Kami

**Comment by Kami** [comment]
Yeah, i think there are some existing issues for it already.

In any case, depending on the priority, I can spend time on doing it this or next week.

**Comment by jjm** [comment]
This would be great, it took some effort to find the required subset of local setup needed to make running pack tests functonal in our internal pack.

**Comment by Kami** [comment]
Just a heads up - I decided I will move those scripts to st2sdk to begin with. This way users who wish to utilize this functionality just need to install st2sdk from PyPi.

Makefile itself is somewhat coupled to a specific directory layout, but I will see what I can do to make it usable outside of here (at the very least, I will document the scripts and targets).

**Comment by manasdk** [comment]
@kami Just moving scripts out is a big win. Don't worry about refactoring the Makefile since that will more often than not be repo specific anyway.

**Comment by Kami** [comment]
Alright, I have polished a bit and moved all the useful check and lint scripts to st2sdk repository and package - https://github.com/StackStorm/st2sdk

For information and examples on how to use those scripts, please refer to the README in that repo and Makefile in this one.

/cc @jjm @tonybaloney
