### ISSUE TITLE
Multiple Vcenter Servers

### ISSUE THREAD

**Issue by makaveli0129** [StackStorm/st2contrib#508]
Is it possible to add multiple Vcenter servers in the config.yaml?

**Comment by paul-mulvihill** [comment]
@makaveli0129  at the moment it's not configured to accept multiple vcenters. Although it is in my list for the next revision of the pack. I need that feature as well.

**Comment by paul-mulvihill** [comment]
@makaveli0129 almost available.
https://github.com/StackStorm/st2contrib/pull/513

**Comment by makaveli0129** [comment]
that's awesome! I will be updating as soon as it's available.

Thanks again

On Thu, Jun 30, 2016 at 4:44 AM, Paul Mulvihill <notifications@github.com>
wrote:

> @makaveli0129 <https://github.com/makaveli0129> almost available.
> #513 <https://github.com/StackStorm/st2contrib/pull/513>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/StackStorm/st2contrib/issues/508#issuecomment-229599043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFBxkKvrLhBnlvpmmwp9WQtHSgxA8gWZks5qQ4IAgaJpZM4I2XdY>
> .
>



-- 
Sincerely,

Shawn H. Marks

**Comment by paul-mulvihill** [comment]
@makaveli0129 we have a merge.. so you should be good to go. shout if any problems or questions.

**Comment by Kami** [comment]
Resolved by #513.

Thanks again!
