### ISSUE TITLE
[git] feature request - I want to specify multiple repository

### ISSUE THREAD

**Issue by userlocalhost2000** [StackStorm/st2contrib#589]
Thank you for creating git pack. It's so useful for me!

But now `git.GitCommitSensor` monitors only one repository which is specified in configuration of this pack.

If it could monitor multiple repositories and branches, it would be more useful.

Thank you.

**Comment by Kami** [comment]
Hello,

This should be a relatively easy change - you should update configuration file so it takes a list of objects where each item contains URL and branch name. Then you need to update the code to handle multiple repos (shouldn't be hard as well).

**Comment by userlocalhost2000** [comment]
Hi Kami

Thank you for your reply.
You got it and I'll do it!

**Comment by userlocalhost2000** [comment]
This feature has been implemented and merged.
Thank you.

**Comment by Kami** [comment]
Thanks again!
