### ISSUE TITLE
hpe-icsp pack - change to underscore

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2contrib#615]
Looks like the hpe-icsp pack is the only one left with `-` in the name and pack ref, not `_`. This won't pass the new validation ( [a-z0-9_] )

What do you want to do about it @jjm / @Kami / @paul-mulvihill ?

I could just go ahead and change it, but it will probably break some of your workflows...

**Comment by paul-mulvihill** [comment]
Apologies I missed/forgot the talks about getting rid of the -. I'm happy to do a new PR in the next day or so to switch it over to a _.
I'm probably the only user of it anyway so i can tie it in with all my other dev work :)

**Comment by LindsayHill** [comment]
Thanks @paul-mulvihill. Better if you do it since you're working with it. I didn't want to break your stuff without at least letting you know

**Comment by paul-mulvihill** [comment]
Created https://github.com/StackStorm/st2contrib/pull/619 to sort this.

**Comment by Kami** [comment]
Resolved by #619 - thanks!
