### ISSUE TITLE
Unable to deploy the newrelic pack in Stackstorm server

### ISSUE THREAD

**Issue by voodemsanthosh** [StackStorm/st2contrib#630]
Hey,

we are trying to clone the stackstorm newrelic pack with stackstorm server, and getting some issue to find the repo.

Here is the error log for deployment failures,

{
  "result": "None",
  "exit_code": 1,
  "stderr": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 211, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py\", line 126, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/packs/actions/check_auto_deploy_repo.py\", line 41, in run\n    raise ValueError(\"No repositories or auto_deployment config for '%s'\" % repo_name)\nValueError: No repositories or auto_deployment config for 'https://github.com/StackStorm/st2contrib/tree'\n",
  "stdout": ""
}

 Please revert your answer with voodem_santhosh@optum.com

Thank you in advance.

**Comment by Kami** [comment]
Just to clarify it - it looks like this is related to deploying / installing a pack from ChatOps.

For that to work, you need to configure config file for `packs` pack, see https://github.com/StackStorm/st2/blob/master/contrib/packs/config.yaml#L4 for example.

**Comment by voodemsanthosh** [comment]
Could you please provide the document to how to configure the new relic alerts to stackstorm.

Example:
I have a server configured in newrelic and if it is utilize X% CPU newrelic will generate the alert.

I need to send the same newrelic alert to stackstorm.

Please provide the sets and document to integrate newrelic alerts with stackstorm.

Thank you in advance.

**Comment by voodemsanthosh** [comment]
Running the newrelic_get_alert by providing app_name and getting below error,

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 211, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 126, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/newrelic/actions/get_alerts.py", line 24, in run
    resp = requests.get(self.url, headers=self.headers, params=params).json()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

who do I configure SSL or do we have any chance to by pass the SSL?

**Comment by LindsayHill** [comment]
Closing this in favour of duplicate https://github.com/StackStorm/st2contrib/issues/639
